---
apiVersion: v1
kind: pack
spec:
  name: hardware-monitoring
  queries:
  - description: Report current fan speeds in the target OSX system.
    interval: 0
    name: fan_speeds
    platform: darwin
    query: fan_speeds
    version: 1.7.1
  - description: Hash files related to EFI platform updates and EFI bootloaders on
      primary boot partition. This does not hash bootloaders on the EFI/boot partition.
    interval: 0
    name: efi_file_hashes
    platform: darwin
    query: efi_file_hashes
    removed: false
    version: 1.6.1
  - description: General reporting and heuristics monitoring.
    interval: 0
    name: acpi_tables
    platform: posix
    query: acpi_tables
    version: 1.3.0
  - description: Retrieves all the information about the current kernel extensions
      for the target OSX system.
    interval: 7200
    name: kernel_extensions
    platform: darwin
    query: kernel_extensions
    version: 1.4.5
  - description: Retrieves all the information for the current kernel modules in the
      target Linux system.
    interval: 7200
    name: kernel_modules
    platform: linux
    query: kernel_modules
    version: 1.4.5
  - description: Inventory all 'device' nodes in /dev/.
    interval: 7200
    name: device_nodes
    platform: posix
    query: device_nodes
    version: 1.6.0
  - description: Report on crashes, alternate boots, and boot arguments.
    interval: 0
    name: nvram
    platform: darwin
    query: nvram
    version: 1.0.2
  - description: Report an inventory of USB devices. Attaches and detaches will show
      up in hardware_events.
    interval: 0
    name: usb_devices
    platform: posix
    query: usb_devices
    version: 1.2.0
  - description: General inventory of IOKit's devices on OS X.
    interval: 0
    name: iokit_devicetree
    platform: darwin
    query: iokit_devicetree
    version: 1.3.0
  - description: Retrieves all the information for the current windows drivers in
      the target Windows system.
    interval: 7200
    name: windows_drivers
    platform: windows
    query: windows_drivers
    version: 2.2.0
  - description: Report current machine temperatures in the target OSX system.
    interval: 0
    name: temperatures
    platform: darwin
    query: temperatures
    version: 1.7.1
  - description: General reporting and heuristics monitoring.
    interval: 0
    name: smbios_tables
    platform: posix
    query: smbios_tables
    version: 1.3.0
  - description: Report the booted kernel, potential arguments, and the device.
    interval: 0
    name: kernel_info
    query: kernel_info
    version: 1.4.0
  - description: Report an inventory of PCI devices. Attaches and detaches will show
      up in hardware_events.
    interval: 0
    name: pci_devices
    platform: posix
    query: pci_devices
    version: 1.0.4
  - description: Retrieves all the hardware related events in the target OSX system.
    interval: 0
    name: hardware_events
    platform: posix
    query: hardware_events
    removed: false
    version: 1.4.5
  - description: Double check the information reported in kernel_info and report the
      kernel signature.
    interval: 0
    name: darwin_kernel_system_controls
    platform: darwin
    query: darwin_kernel_system_controls
    version: 1.4.3
  - description: General reporting and heuristics monitoring.
    interval: 0
    name: cpuid
    query: cpuid
    version: 1.0.4
  targets:
    labels: null
---
apiVersion: v1
kind: query
spec:
  description: Report current fan speeds in the target OSX system.
  name: fan_speeds
  query: select * from fan_speed_sensors;
---
apiVersion: v1
kind: query
spec:
  description: Hash files related to EFI platform updates and EFI bootloaders on primary
    boot partition. This does not hash bootloaders on the EFI/boot partition.
  name: efi_file_hashes
  query: select file.path, uid, gid, mode, 0 as atime, mtime, ctime, md5, sha1, sha256
    from (select * from file where path like '/System/Library/CoreServices/%.efi'
    union select * from file where path like '/System/Library/LaunchDaemons/com.apple%efi%')
    file join hash using (path);
---
apiVersion: v1
kind: query
spec:
  description: General reporting and heuristics monitoring.
  name: acpi_tables
  query: select * from acpi_tables;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the information about the current kernel extensions for
    the target OSX system.
  name: kernel_extensions
  query: select * from kernel_extensions;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the information for the current kernel modules in the
    target Linux system.
  name: kernel_modules
  query: select * from kernel_modules;
---
apiVersion: v1
kind: query
spec:
  description: Inventory all 'device' nodes in /dev/.
  name: device_nodes
  query: select file.path, uid, gid, mode, 0 as atime, mtime, ctime, block_size, type
    from file where directory = '/dev/';
---
apiVersion: v1
kind: query
spec:
  description: Report on crashes, alternate boots, and boot arguments.
  name: nvram
  query: select * from nvram where name not in ('backlight-level', 'SystemAudioVolumeDB',
    'SystemAudioVolume');
---
apiVersion: v1
kind: query
spec:
  description: Report an inventory of USB devices. Attaches and detaches will show
    up in hardware_events.
  name: usb_devices
  query: select * from usb_devices;
---
apiVersion: v1
kind: query
spec:
  description: General inventory of IOKit's devices on OS X.
  name: iokit_devicetree
  query: select * from iokit_devicetree;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the information for the current windows drivers in the
    target Windows system.
  name: windows_drivers
  query: select * from drivers;
---
apiVersion: v1
kind: query
spec:
  description: Report current machine temperatures in the target OSX system.
  name: temperatures
  query: select * from temperature_sensors;
---
apiVersion: v1
kind: query
spec:
  description: General reporting and heuristics monitoring.
  name: smbios_tables
  query: select * from smbios_tables;
---
apiVersion: v1
kind: query
spec:
  description: Report the booted kernel, potential arguments, and the device.
  name: kernel_info
  query: select * from kernel_info join hash using (path);
---
apiVersion: v1
kind: query
spec:
  description: Report an inventory of PCI devices. Attaches and detaches will show
    up in hardware_events.
  name: pci_devices
  query: select * from pci_devices;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the hardware related events in the target OSX system.
  name: hardware_events
  query: select * from hardware_events where path <> '' or model <> '';
---
apiVersion: v1
kind: query
spec:
  description: Double check the information reported in kernel_info and report the
    kernel signature.
  name: darwin_kernel_system_controls
  query: select * from system_controls where subsystem = 'kern' and (name like '%boot%'
    or name like '%secure%' or name like '%single%');
---
apiVersion: v1
kind: query
spec:
  description: General reporting and heuristics monitoring.
  name: cpuid
  query: select feature, value, output_register, output_bit, input_eax from cpuid;
