---
apiVersion: v1
kind: pack
spec:
  name: vuln-management
  queries:
  - description: Retrieves all the installed DEB packages in the target Linux system.
    interval: 86400
    name: deb_packages
    platform: linux
    query: deb_packages
    version: 1.4.5
  - description: Watches for the backdoored Python packages installed on system. See
      (http://www.nbu.gov.sk/skcsirt-sa-20170909-pypi/index.html)
    interval: 86400
    name: backdoored_python_packages
    platform: posix
    query: backdoored_python_packages
    version: 1.4.5
  - description: Retrieves information from the current kernel in the target system.
    interval: 86400
    name: kernel_info
    query: kernel_info
    version: 1.4.5
  - description: Retrieves all the information for the current kernel modules in the
      target Linux system.
    interval: 86400
    name: kernel_modules
    platform: linux
    query: kernel_modules
    version: 1.4.5
  - description: Retrieves all the currently installed applications in the target
      OSX system.
    interval: 86400
    name: installed_applications
    platform: darwin
    query: installed_applications
    version: 1.4.5
  - description: Retrieves the list of C/NPAPI browser plugins in the target system.
    interval: 86400
    name: browser_plugins
    platform: darwin
    query: browser_plugins
    version: 1.6.1
  - description: Retrieves the list of extensions for Safari in the target system.
    interval: 86400
    name: safari_extensions
    platform: darwin
    query: safari_extensions
    version: 1.6.1
  - description: Retrieves all the information about the current kernel extensions
      for the target OSX system.
    interval: 86400
    name: kextstat
    platform: darwin
    query: kextstat
    version: 1.4.5
  - description: Retrieves the list of brew packages installed in the target OSX system.
    interval: 86400
    name: homebrew_packages
    platform: darwin
    query: homebrew_packages
    version: 1.4.5
  - description: Retrieves all the APT sources to install packages from in the target
      Linux system.
    interval: 86400
    name: apt_sources
    platform: linux
    query: apt_sources
    version: 1.4.5
  - description: Retrieves all the installed packages on the target Linux system.
    interval: 86400
    name: portage_packages
    platform: linux
    query: portage_packages
    version: 2.0.0
  - description: Retrieves all application bundles using unauthenticated Sparkle update
      feeds. See (https://vulnsec.com/2016/osx-apps-vulnerabilities/) for details.
    interval: 86400
    name: unauthenticated_sparkle_feeds
    platform: darwin
    query: unauthenticated_sparkle_feeds
    version: 1.4.5
  - description: Retrieves the current version of the running osquery in the target
      system and where the configuration was loaded from.
    interval: 86400
    name: os_version
    query: os_version
    version: 1.4.5
  - description: Retrieves the list of extensions for Chrome in the target system.
    interval: 86400
    name: chrome_extensions
    query: chrome_extensions
    version: 1.6.1
  - description: Retrieves all the PKG related information stored in OSX.
    interval: 86400
    name: package_receipts
    platform: darwin
    query: package_receipts
    version: 1.4.5
  - description: Retrieves the list of extensions for Opera in the target system.
    interval: 86400
    name: opera_extensions
    platform: posix
    query: opera_extensions
    version: 1.6.1
  - description: Retrieves the list of addons for Firefox in the target system.
    interval: 86400
    name: firefox_addons
    platform: posix
    query: firefox_addons
    version: 1.6.1
  - description: Retrieves all the installed RPM packages in the target Linux system.
    interval: 86400
    name: rpm_packages
    platform: linux
    query: rpm_packages
    version: 1.4.5
  targets:
    labels: null
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the installed DEB packages in the target Linux system.
  name: deb_packages
  query: select * from deb_packages;
---
apiVersion: v1
kind: query
spec:
  description: Watches for the backdoored Python packages installed on system. See
    (http://www.nbu.gov.sk/skcsirt-sa-20170909-pypi/index.html)
  name: backdoored_python_packages
  query: select name as package_name, version as package_version, path as package_path
    from python_packages where package_name = 'acqusition' or package_name = 'apidev-coop'
    or package_name = 'bzip' or package_name = 'crypt' or package_name = 'django-server'
    or package_name = 'pwd' or package_name = 'setup-tools' or package_name = 'telnet'
    or package_name = 'urlib3' or package_name = 'urllib';
---
apiVersion: v1
kind: query
spec:
  description: Retrieves information from the current kernel in the target system.
  name: kernel_info
  query: select * from kernel_info;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the information for the current kernel modules in the
    target Linux system.
  name: kernel_modules
  query: select * from kernel_modules;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the currently installed applications in the target OSX
    system.
  name: installed_applications
  query: select * from apps;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the list of C/NPAPI browser plugins in the target system.
  name: browser_plugins
  query: select browser_plugins.* from users join browser_plugins using (uid);
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the list of extensions for Safari in the target system.
  name: safari_extensions
  query: select safari_extensions.* from users join safari_extensions using (uid);
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the information about the current kernel extensions for
    the target OSX system.
  name: kextstat
  query: select * from kernel_extensions;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the list of brew packages installed in the target OSX system.
  name: homebrew_packages
  query: select * from homebrew_packages;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the APT sources to install packages from in the target
    Linux system.
  name: apt_sources
  query: select * from apt_sources;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the installed packages on the target Linux system.
  name: portage_packages
  query: select * from portage_packages;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all application bundles using unauthenticated Sparkle update
    feeds. See (https://vulnsec.com/2016/osx-apps-vulnerabilities/) for details.
  name: unauthenticated_sparkle_feeds
  query: select feeds.*, p2.value as sparkle_version from (select a.name as app_name,
    a.path as app_path, a.bundle_identifier as bundle_id, p.value as feed_url from
    (select name, path, bundle_identifier from apps) a, plist p where p.path = a.path
    || '/Contents/Info.plist' and p.key = 'SUFeedURL' and feed_url like 'http://%')
    feeds left outer join plist p2 on p2.path = app_path || '/Contents/Frameworks/Sparkle.framework/Resources/Info.plist'
    where (p2.key = 'CFBundleShortVersionString' OR coalesce(p2.key, '') = '');
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the current version of the running osquery in the target
    system and where the configuration was loaded from.
  name: os_version
  query: select * from os_version;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the list of extensions for Chrome in the target system.
  name: chrome_extensions
  query: select chrome_extensions.* from users join chrome_extensions using (uid);
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the PKG related information stored in OSX.
  name: package_receipts
  query: select * from package_receipts;
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the list of extensions for Opera in the target system.
  name: opera_extensions
  query: select opera_extensions.* from users join opera_extensions using (uid);
---
apiVersion: v1
kind: query
spec:
  description: Retrieves the list of addons for Firefox in the target system.
  name: firefox_addons
  query: select firefox_addons.* from users join firefox_addons using (uid);
---
apiVersion: v1
kind: query
spec:
  description: Retrieves all the installed RPM packages in the target Linux system.
  name: rpm_packages
  query: select * from rpm_packages;
